### ISSUE TITLE
3D Spatial Transform Network

### ISSUE THREAD

**Issue by mohamedhassanmus** [Salingo/PGDNN#1]
Hi,
I see you did the 3d transform in 2 step as in:
https://github.com/Salingo/PGDNN/blob/f775d0eac2027b5b62559b8ab474da2b06bf6767/Code/iGEN-NET/network.py#L142

Is there any specific reason for that? Wouldn't it be possible to perform the 3d transform in one go?
Also I can't find the supplementary materials. It would be good if you can point to that.

Thanks!

**Comment by Salingo** [comment]
Sorry for the late reply. When we were trying to use this transformation method, xy and z dim are transformed separately because it's easy to debug, I think it is possible to perform 3d trans in one step.
The supplementary materials are uploaded here, but the image quality is not good due to the upload limit, we will upload the original version on our project page later.
[supp.pdf](https://github.com/Salingo/PGDNN/files/2434202/supp.pdf)
