### ISSUE TITLE
Ground truth for scale and translation

### ISSUE THREAD

**Issue by mohamedhassanmus** [Salingo/PGDNN#3]
I wonder how was the ground truth for the scale and translation generated? 
Can you provide some details? Thanks.

**Comment by ruizhenh** [comment]
Since both the individual central object and the corresponding scene are scaled into same unit cute, the ground truth for the scale and translation is computed by comparing the bbox of the scene and the bbox of the central object inside the scene. More specifically, scale is computed as the ratio of their diagonals and translation is computed to match their centers.

**Comment by ruizhenh** [comment]
> I wonder how was the ground truth for the scale and translation generated?
> Can you provide some details? Thanks.

Since both the individual central object and the corresponding scene are scaled into same unit cute, the ground truth for the scale and translation is computed by comparing the bbox of the scene and the bbox of the central object inside the scene. More specifically, scale is computed as the ratio of their diagonals and translation is computed to match their centers.
